{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  001_create_db.sh: |-
    psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
      CREATE USER ${POSTGRES_APP_USER} WITH PASSWORD '${POSTGRES_APP_PASSWORD}';
      CREATE DATABASE ${POSTGRES_APP_DB};
      GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_APP_DB} TO ${POSTGRES_APP_USER};
    EOSQL
{{- end -}}
