{{- if and .Values.enabled .Values.persistentVolume.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
{{- if .Values.persistentVolume.storageClass }}
  storageClassName: {{ .Values.persistentVolume.storageClass | quote }}
{{- end -}}
{{- end -}}
