{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.postgresqlPassword | default "" | ne "" }}
  postgresql-password: {{ .Values.postgresqlPassword | b64enc | quote }}
  {{- else }}
  postgresql-password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end -}}
  {{- if .Values.postgresqlSuPassword | default "" | ne "" }}
  postgresql-su-password: {{ .Values.postgresqlSuPassword | b64enc | quote }}
  {{- else }}
  postgresql-su-password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end -}}
{{- end -}}
