apiVersion: v1
kind: Secret
metadata:
  name: {{ template "omgshop.fullname" . }}
  labels:
    app: {{ template "omgshop.name" . }}
    chart: {{ template "omgshop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.omgshopSecretKey | default "" | ne "" }}
  omgshop-secret-key: {{ .Values.omgshopSecretKey | b64enc | quote }}
  {{- else }}
  omgshop-secret-key: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end -}}
