Metrics/LineLength:
  Max: 100
Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 23
Metrics/AbcSize:
  Enabled: false
AllCops:
  Exclude:
    - 'db/schema.rb'
